const BASE_HANDS = [{id:'scissors',name:'가위',icon:'✌️',owner:'base'},{id:'rock',name:'바위',icon:'✊',owner:'base'},{id:'paper',name:'보',icon:'🖐️',owner:'base'}];
const EMOJIS=['🌪️','🔥','🧊','⚡','🌙','🌈','🪨','🦊','👻','🍀'];
const state={players:[makePlayer(),makePlayer()],editing:0,selections:[null,null],revealed:false,scores:[0,0],round:1,history:[]};
function makePlayer(){return {cards:[{name:'',icon:'🌪️',beats:[]},{name:'',icon:'🔥',beats:[]}]};}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function allHands(){return [...BASE_HANDS,...state.players.flatMap((p,pi)=>p.cards.map((c,ci)=>({id:`p${pi}c${ci}`,name:c.name||`창작 패 ${ci+1}`,icon:c.icon,owner:pi})))];}
function renderSetup(){const p=state.players[state.editing], other=state.players[1-state.editing];$('#setupTitle').textContent=`플레이어 ${state.editing+1}의 창작 패`;$('#customGrid').innerHTML=p.cards.map((card,i)=>`<article class="custom-card"><div class="custom-card-title"><b>창작 패 ${i+1}</b><span>PLAYER ${state.editing+1}</span></div><label class="field-label">패 이름</label><input class="name-input" data-card="${i}" value="${escapeHtml(card.name)}" placeholder="예: 번개" maxlength="8"/><label class="field-label rule-label">패 아이콘</label><div class="emoji-row">${EMOJIS.map(e=>`<button class="emoji-button ${card.icon===e?'selected':''}" data-emoji="${e}" data-card="${i}">${e}</button>`).join('')}</div><label class="field-label rule-label">이 패가 이기는 대상</label><p class="rule-help">기본 3장과 공개될 상대 패 중 선택</p><div class="rule-options">${BASE_HANDS.map(h=>ruleBox(h,card,i)).join('')}${other.cards.map((h,j)=>ruleBox({id:`p${1-state.editing}c${j}`,name:h.name||`상대 패 ${j+1}`,icon:h.icon},card,i)).join('')}</div></article>`).join('');
  $$('.name-input').forEach(el=>el.addEventListener('input',e=>p.cards[+e.target.dataset.card].name=e.target.value));$$('.emoji-button').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();p.cards[+el.dataset.card].icon=el.dataset.emoji;renderSetup()}));$$('.rule-input').forEach(el=>el.addEventListener('change',e=>{const c=p.cards[+e.target.dataset.card],id=e.target.value;c.beats=e.target.checked?[...c.beats,id]:c.beats.filter(x=>x!==id)}));}
function ruleBox(h,c,i){return `<label class="rule-check"><input class="rule-input" type="checkbox" data-card="${i}" value="${h.id}" ${c.beats.includes(h.id)?'checked':''}/> ${h.icon} ${h.name}</label>`}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function judgeRules(){const hands=allHands(), findings=[]; state.players.forEach((p,pi)=>p.cards.forEach((c,ci)=>{const h=hands.find(x=>x.id===`p${pi}c${ci}`), wins=hands.filter(x=>x.id!==h.id&&outcome(h,x)==='win'), losses=hands.filter(x=>x.id!==h.id&&outcome(h,x)==='lose');if(!wins.length)findings.push(`「${h.name}」는 이기는 대상이 없어 사기 패가 될 수 없습니다.`);if(!losses.length)findings.push(`「${h.name}」는 지는 대상이 없어 사기 패가 될 수 없습니다.`);if(wins.length>=hands.length-2)findings.push(`「${h.name}」의 승리 대상이 너무 많아 밸런스가 무너집니다.`);}));const duplicates=hands.filter((h,i)=>hands.findIndex(x=>x.name.trim()===h.name.trim())!==i);if(duplicates.length)findings.push(`「${duplicates[0].name}」과 같은 이름의 패가 있어 구분할 수 없습니다.`);return {ok:!findings.length,findings};}
async function goMatrix(){if(state.players.some(p=>p.cards.some(c=>!c.name.trim()))){alert('두 창작 패의 이름을 모두 입력해 주세요.');return}const box=$('#aiReview');box.className='ai-review';box.classList.remove('hidden');box.innerHTML='<b>✦ AI 심판이 규칙을 분석 중…</b><p>상성 방향, 모순, 사기 패 여부를 함께 확인하고 있어요.</p>';$('#nextSetup').disabled=true;try{const response=await fetch('/api/judge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({hands:allHands(),players:state.players})});const result=await response.json();if(!response.ok)throw new Error(result.error||'AI 심판 서버에 연결할 수 없습니다.');const engine=result.engine==='gemini'?'Gemini AI':'로컬 테스트';box.className=`ai-review ${result.approved?'ok':'fail'}`;if(result.approved){box.innerHTML=`<b>✦ ${engine} 심판: 통과</b><p>${escapeHtml(result.summary)}</p><button class="review-action" id="revealRules">상성표 공개하기 →</button>`;$('#nextSetup').classList.add('hidden');$('#revealRules').addEventListener('click',revealMatrix);}else{box.innerHTML=`<b>⚠ ${engine} 심판: 수정 필요</b><p>${(result.reasons||['규칙에 모순이 있습니다.']).map(escapeHtml).join('<br>')}</p><p>상성을 수정한 뒤 다시 AI 심판을 실행해 주세요.</p>`;$('#nextSetup').disabled=false;}}catch(error){box.className='ai-review fail';box.innerHTML=`<b>⚠ AI 심판 연결 실패</b><p>${escapeHtml(error.message)}</p><p>서버를 실행하고 GEMINI_API_KEY를 설정한 뒤 다시 시도해 주세요.</p>`;$('#nextSetup').disabled=false;}}
function revealMatrix(){state.editing=0;$('#setupView').classList.add('hidden');$('#matrixView').classList.remove('hidden');setPhase(1);renderMatrix();}
function renderMatrix(){const hands=allHands(), head=hands.map(h=>`<th><div class="matrix-hand"><span class="matrix-icon">${h.icon}</span><span class="matrix-name">${h.name}</span></div></th>`).join('');let rows=hands.map(row=>`<tr><th><div class="matrix-hand"><span class="matrix-icon">${row.icon}</span><span class="matrix-name">${row.name}</span></div></th>${hands.map(col=>{const r=outcome(row,col);return `<td class="cell-${r}">${r==='win'?'WIN':r==='lose'?'LOSE':'—'}</td>`}).join('')}</tr>`).join('');$('#matrixTable').innerHTML=`<thead><tr><th><span class="matrix-corner">행 ↓ / 열 →</span></th>${head}</tr></thead><tbody>${rows}</tbody>`;}
function outcome(a,b){if(a.id===b.id)return 'draw';const aBeats=beats(a,b),bBeats=beats(b,a);if(aBeats&&!bBeats)return 'win';if(bBeats&&!aBeats)return 'lose';return 'draw'}
function beats(a,b){if(a.owner==='base')return baseBeats[a.id]?.includes(b.id)||false;return state.players[a.owner].cards[+a.id.slice(-1)].beats.includes(b.id)}
const baseBeats={scissors:['paper'],rock:['scissors'],paper:['rock']};
function startBattle(){state.revealed=true;$('#matrixView').classList.add('hidden');$('#battleView').classList.remove('hidden');setPhase(2);renderBattle();}
function renderBattle(){state.players.forEach((p,pi)=>{const hands=[...BASE_HANDS,...p.cards.map((c,i)=>({id:`p${pi}c${i}`,name:c.name,icon:c.icon,owner:pi}))];$(`#handOptions${pi}`).innerHTML=hands.map(h=>`<button class="hand-option ${state.selections[pi]===h.id?'selected':''}" data-player="${pi}" data-hand="${h.id}"><span class="matrix-icon">${h.icon}</span><small>${h.name}</small></button>`).join('');$$(`#handOptions${pi} .hand-option`).forEach(el=>el.addEventListener('click',()=>{state.selections[+el.dataset.player]=el.dataset.hand;renderBattle()}));});$('#score0').textContent=state.scores[0];$('#score1').textContent=state.scores[1];$('#roundLabel').textContent=`ROUND ${state.round}`;$('#picked0').textContent=state.selections[0]?'준비 완료':'선택 전';$('#picked1').textContent=state.selections[1]?'준비 완료':'선택 전';}
function launch(){if(state.selections.some(x=>!x)){alert('두 플레이어 모두 패를 선택해 주세요.');return}const hands=allHands(),a=hands.find(h=>h.id===state.selections[0]),b=hands.find(h=>h.id===state.selections[1]),r=outcome(a,b);let text='무승부';if(r==='win'){state.scores[0]++;text='플레이어 1 승';}else if(r==='lose'){state.scores[1]++;text='플레이어 2 승';}state.history.unshift({round:state.round,a,b,text});state.round++;state.selections=[null,null];renderBattle();$('#battleStatus').textContent=`${a.icon} ${a.name}  vs  ${b.icon} ${b.name}  ·  ${text}${text==='무승부'?' — 다시 한 번!':''}`;$('#battleLogList').innerHTML=state.history.map(x=>`<div class="log-item"><span>R${x.round} · ${x.a.icon} ${x.a.name} <b>vs</b> ${x.b.icon} ${x.b.name}</span><strong>${x.text}</strong></div>`).join('');if(state.scores.some(s=>s>=5)){const winner=state.scores[0]>=5?1:2;setTimeout(()=>{ $('#winnerTitle').textContent=`플레이어 ${winner} 승리!`;$('#winnerCopy').textContent=`${state.scores[winner-1]}점을 먼저 모으며 상성 전쟁의 승자가 되었어요.`;$('#resultModal').classList.remove('hidden')},350)}}
function setPhase(n){$('#phasePill').textContent=['규칙 설계','상성 확인','승부 중'][n];$$('.step').forEach((el,i)=>el.classList.toggle('active',i===n));}
$$('.player-tab').forEach(el=>el.addEventListener('click',()=>{state.editing=+el.dataset.player;$$('.player-tab').forEach(x=>x.classList.toggle('selected',x===el));renderSetup()}));$('#nextSetup').addEventListener('click',()=>{if(state.editing===0){state.editing=1;$$('.player-tab')[1].click();}else goMatrix()});$('#startBattle').addEventListener('click',startBattle);$$('.launch-button').forEach(b=>b.addEventListener('click',launch));$('#resetButton').addEventListener('click',()=>location.reload());$('#playAgain').addEventListener('click',()=>location.reload());renderSetup();
