const BASE=[{id:'scissors',name:'가위',icon:'✌️',owner:'base'},{id:'rock',name:'바위',icon:'✊',owner:'base'},{id:'paper',name:'보',icon:'🖐️',owner:'base'}];
const $=s=>document.querySelector(s), sessionKey='glyco-online-room'; let session=JSON.parse(sessionStorage.getItem(sessionKey)||'null'), game=null, choice=null, finalizing=false, resolving=false;
const busy=(on,text='규칙을 분석하고 있어요…')=>{$('#busy').classList.toggle('hidden',!on);$('#busyText').textContent=text};
async function api(action,data={}){const r=await fetch('/api/room',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const d=await r.json();if(!r.ok)throw new Error(d.error||'방 요청에 실패했습니다.');return d}
async function judge(data){const r=await fetch('/api/judge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI 판정에 실패했습니다.');return d}
function saveSession(data){session={roomCode:data.roomCode,token:data.token,slot:data.slot};sessionStorage.setItem(sessionKey,JSON.stringify(session));game={room:data.room,players:data.players};render();poll()}
function own(){return game?.players.find(p=>p.slot===session.slot)} function opponent(){return game?.players.find(p=>p.slot!==session.slot)}
function cards(player){return player?.cards?.length===2?player.cards:[{name:'',ruleText:'',beats:[],saved:false},{name:'',ruleText:'',beats:[],saved:false}]}
function allHands(){return [...BASE,...game.players.flatMap((p,i)=>cards(p).map((c,j)=>({id:`p${i}c${j}`,name:c.name||`창작 패 ${j+1}`,icon:c.icon||'✨',owner:i})))];}
function lobby(){return `<section class="room-card"><h2>친구와 방에서 대결하세요</h2><p>각자 창작 패 두 장을 만들고 준비하면, Gemini AI가 실제 5×5 상성표를 심사합니다.</p><div class="room-grid"><form class="room-form" id="createForm"><h3>방 만들기</h3><input name="name" maxlength="12" placeholder="내 이름 (선택)"/><button class="room-action">새 방 만들기</button></form><form class="room-form" id="joinForm"><h3>방 참가하기</h3><input name="code" maxlength="6" placeholder="초대 코드 6자리" required/><input name="name" maxlength="12" placeholder="내 이름 (선택)"/><button class="room-action">방 참가하기</button></form></div></section>`}
function setup(){const me=own(), other=opponent(), mine=cards(me);return `<section class="room-card"><div class="room-banner"><div><small>초대 코드</small><div class="room-code">${session.roomCode}</div><small>친구에게 이 코드를 보내세요.</small></div><button class="room-action" id="copyCode" style="width:auto">코드 복사</button></div><div class="player-status">${game.players.map(p=>`<div><b>${p.name}</b><span class="${p.ready?'ready':'waiting'}">${p.ready?'✓ 준비 완료':'○ 규칙 작성 중'}</span></div>`).join('')}</div>${game.room.status==='reviewing'?`<p>두 플레이어가 준비되었습니다. Gemini AI가 최종 5×5 상성을 심사 중입니다.</p>`:''}<h2>${me.name}의 창작 패</h2><p>상대는 내 규칙을 볼 수 없어요. 각 패는 저장할 때 Gemini AI의 예비 검사를 통과해야 합니다.</p><div class="room-grid">${mine.map((c,i)=>`<article class="online-card"><h3>창작 패 ${i+1}</h3><input data-name="${i}" value="${esc(c.name||'')}" placeholder="패 이름" ${me.ready?'disabled':''}/><textarea data-rule="${i}" placeholder="예: 번개는 가위를 이기지만 바위에게는 진다." ${me.ready?'disabled':''}>${esc(c.ruleText||'')}</textarea><button data-save="${i}" ${me.ready?'disabled':''}>저장하고 AI 검사하기</button><small class="${c.saved?'ok':''}" id="note${i}">${c.saved?'개별 검사 통과 · 최종 5×5 검사 대기':'사기 규칙은 등록할 수 없어요.'}</small></article>`).join('')}</div><button class="room-action" id="ready" ${me.ready?'disabled':''}>${me.ready?'준비 완료 · 상대를 기다리는 중':'두 패 준비 완료'}</button></section>`}
function battle(){const me=own(), myHands=[...BASE,...cards(me).map((c,i)=>({id:`p${session.slot-1}c${i}`,name:c.name,icon:c.icon||'✨'}))], other=opponent();return `<section class="room-card"><div class="room-banner"><div><b>${me.name} ${me.score}점</b> : <b>${other.name} ${other.score}점</b><p>${game.room.last_result?.reason||'패를 고르고 제출하세요.'}</p></div><span class="room-code">BATTLE</span></div><h2>내 패를 선택하세요</h2><div class="battle-options">${myHands.map(h=>`<button data-choice="${h.id}" class="${choice===h.id?'selected':''}"><span style="font-size:22px">${h.icon}</span><br/><small>${h.name}</small></button>`).join('')}</div><button class="room-action" id="submitChoice" ${!choice?'disabled':''}>패 제출하기</button><p>${me.choice?'내 선택 완료 · 상대를 기다리는 중':'상대에게 보이지 않게 패를 고르세요.'}</p></section>`}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(){const root=$('#app');root.innerHTML=!session?lobby():!game?'<section class="room-card">방 정보를 불러오는 중…</section>':game.room.status==='battle'?battle():setup();if(!session){$('#createForm').onsubmit=async e=>{e.preventDefault();try{saveSession(await api('create',{name:e.target.name.value}))}catch(x){alert(x.message)}};$('#joinForm').onsubmit=async e=>{e.preventDefault();try{saveSession(await api('join',{roomCode:e.target.code.value,name:e.target.name.value}))}catch(x){alert(x.message)}};return}if(game.room.status==='battle'){document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{choice=b.dataset.choice;render()});$('#submitChoice').onclick=submitChoice;return}$('#copyCode').onclick=()=>navigator.clipboard?.writeText(session.roomCode);document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveCard(+b.dataset.save));$('#ready').onclick=ready}
async function saveCard(i){const me=own(), mine=cards(me), name=$(`[data-name="${i}"]`).value.trim(), ruleText=$(`[data-rule="${i}"]`).value.trim();if(!name||!ruleText)return alert('이름과 규칙 문장을 입력해 주세요.');busy(true,'창작 패가 사기 규칙인지 예비 검사하고 있어요…');try{const card={...mine[i],name,ruleText,icon:mine[i].icon||'✨'}, result=await judge({mode:'card',card:{id:`p${session.slot-1}c${i}`,...card},hands:allHands(),players:game.players.map(p=>({cards:cards(p)}))});if(!result.approved)throw new Error((result.reasons||[]).join(' '));mine[i]={...card,beats:result.beats||[],saved:true};await api('saveCards',{roomCode:session.roomCode,token:session.token,cards:mine});await refresh()}catch(e){alert(`등록 거부: ${e.message}`)}finally{busy(false)}}
async function ready(){const me=own();if(cards(me).some(c=>!c.saved))return alert('두 패를 각각 저장하고 AI 검사를 통과해 주세요.');await api('ready',{roomCode:session.roomCode,token:session.token});await refresh()}
async function finalize(){if(finalizing||session.slot!==1)return;finalizing=true;busy(true,'양쪽의 5장을 비교해 최종 5×5 상성표를 심사하고 있어요…');try{const result=await judge({mode:'register',hands:allHands(),players:game.players.map(p=>({cards:cards(p)}))});const players=game.players.map(p=>({...p,cards:cards(p)}));if(result.approved)(result.normalizedRules||[]).forEach(rule=>{const pi=+rule.id[1],ci=+rule.id.at(-1);players[pi].cards[ci].beats=rule.beats});await api('finalize',{roomCode:session.roomCode,token:session.token,approved:result.approved,finalRules:{players,summary:result.summary,reasons:result.reasons}});if(!result.approved)alert((result.reasons||[]).join('\n'));await refresh()}catch(e){alert(e.message)}finally{busy(false);finalizing=false}}
async function submitChoice(){await api('choose',{roomCode:session.roomCode,token:session.token,choice});choice=null;await refresh()}
async function resolve(){if(resolving||session.slot!==1)return;const ps=game.players;if(ps.some(p=>!p.choice))return;resolving=true;busy(true,'Gemini AI가 선택된 두 패의 승패를 판정하고 있어요…');try{const result=await judge({mode:'battle',hands:allHands(),players:ps.map(p=>({cards:cards(p)})),choices:ps.map(p=>p.choice)});await api('resolve',{roomCode:session.roomCode,token:session.token,winner:result.winner<0?0:result.winner+1,reason:result.reason});await refresh()}catch(e){alert(e.message)}finally{busy(false);resolving=false}}
async function refresh(){if(!session)return;try{const data=await api('state',{roomCode:session.roomCode,token:session.token});game=data;render();if(game.room.status==='reviewing')finalize();if(game.room.status==='battle')resolve()}catch(e){console.warn(e.message)}}
let timer;function poll(){clearInterval(timer);timer=setInterval(refresh,1600);refresh()}render();if(session)poll();
